--- #YAML:1.0
name:                XML-FeedLite
version:             1.006
abstract:            Perl extension for fetching Atom and RSS feeds with minimal outlay
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    HTML::Entities:                
    HTTP::Headers:                 1.64
    HTTP::Request:                 1.4
    LWP::Parallel::UserAgent:      
    MIME::Base64:                  
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Roger Pettett <rmp@psyphi.net>
